server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# JWT
jwt:
  secret: ${JWT_SECRET:digitopia-secret-key-for-jwt-token-min-32-characters-required}
  expiration: 86400000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: healtz

# Logging
logging:
  level:
    com.digitopia.user: DEBUG
    org.hibernate.SQL: DEBUG